name: massh
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cftime=1.5.1.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.1.1
  - dask-core=2023.1.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.1.1
  - docrep=0.3.2
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.1.0
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gsl=2.7
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jax=0.3.25
  - jaxlib=0.3.25
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcurl=7.87.0
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libhwloc=2.8.0
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.8.0
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2022.2.1
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - nettle=3.7.3
  - nspr=4.33
  - nss=3.74
  - numcodecs=0.11.0
  - numexpr=2.8.3
  - numpy=1.24.2
  - openh264=2.1.1
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyinterp=2023.2.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.10
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scipy=1.9.3
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tbb=2021.7.0
  - tblib=1.7.0
  - testpath=0.6.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - x264=1!157.20191217
  - xarray=2022.11.0
  - xrft=1.0.0
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - pyqt5-sip==12.11.0
